import * as THREE from 'three';
import { OrbitControls } from '/vendor/three/addons/controls/OrbitControls.js';
import { STLLoader } from '/vendor/three/addons/loaders/STLLoader.js';
import { expandPauses, makeTimeline } from '/sequence.mjs';
const $=id=>document.getElementById(id), notes=['F','Gb','G','Ab','A','Bb','B','C1','Db1','D1','Eb1','E1','F1','Gb1','G1','Ab1','A1','Bb1','B1','C2'];
const defaultNotes=[...notes,...Array(5).fill('·')].join(' ');
const defaultColors={front:'#538d82',back:'#c4cfbe',clip:'#c98c53'};
let config={notes:defaultNotes,offsets:[],extension:0,layers:[],colors:{...defaultColors}}, selected=-1, metadata=null, timer, revision=0, ready=false, toastTimer;
const toast=text=>{$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',3500)};
async function api(path,data){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok){let error;try{error=(await response.json()).error}catch{error='请求失败'}throw Error(error)}return response}
async function download(format){const file=await(await api('/api/download',{config,format})).json(),a=document.createElement('a');a.href=file.url;a.download=file.filename;document.body.append(a);a.click();a.remove()}
function tokens(){return expandPauses($('sequence').value)}
function updateTuning(){const current=$('tuning-note').selectedIndex,values=tokens();$('count').textContent=`${values.length} / 33`;$('tuning-note').replaceChildren(...values.map((note,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1} · ${note}`;return o}));$('tuning-note').selectedIndex=Math.min(Math.max(current,0),values.length-1);$('offset').value=-(config.offsets[$('tuning-note').selectedIndex]||0)}
function schedule(){config.notes=$('sequence').value;config.offsets=config.offsets.slice(0,tokens().length);ready=false;document.querySelectorAll('[data-export]').forEach(b=>b.disabled=true);$('status').textContent='等待生成…';clearTimeout(timer);revision++;timer=setTimeout(()=>generate(revision),450);drawArt()}
async function generate(version=++revision){
 $('status').textContent='正在生成…';$('error').textContent='';
 try{const result=await (await api('/api/generate',config)).json();if(version!==revision)return;config={...result.config,colors:{...defaultColors,...result.config?.colors}};metadata=result.metadata;ready=true;updateColors();updateTuning();showModel(result.stl,result.meshes);renderLayers();drawArt();$('stat-count').textContent=metadata.count;$('stat-width').textContent=metadata.width.toFixed(2);$('stat-depth').textContent=metadata.depth.toFixed(2);$('stat-colors').textContent=new Set((metadata.materials||Object.values(config.colors).map(color=>({color}))).map(m=>m.color)).size;$('status').textContent='✓ 模型已更新';document.querySelectorAll('[data-export]').forEach(b=>b.disabled=false)}catch(e){if(version!==revision)return;ready=false;$('error').textContent=e.message;$('status').textContent='请检查输入';document.querySelectorAll('[data-export]').forEach(b=>b.disabled=true)}
}
for(const note of [...notes,'·']){const b=document.createElement('button');b.textContent=note;b.title=note==='·'?'添加停顿':`添加 ${note}`;b.onclick=()=>{if(tokens().length>=33){toast('最多 33 个位置');return}$('sequence').value=$('sequence').value.trim()+' '+note;config.offsets.push(0);updateTuning();schedule()};$('note-keys').append(b)}
$('sequence').addEventListener('input',()=>{updateTuning();schedule()});$('scale').onclick=()=>{$('sequence').value=defaultNotes;config.offsets=[];updateTuning();schedule()};$('melody').onclick=()=>{$('sequence').value='C1 C1 G1 G1 A1 A1 G1 · F1 F1 E1 E1 D1 D1 C1';config.offsets=[];updateTuning();schedule()};$('tuning-note').onchange=()=>{$('offset').value=-(config.offsets[+$('tuning-note').value]||0)};$('offset').oninput=()=>{const i=+$('tuning-note').value;while(config.offsets.length<tokens().length)config.offsets.push(0);config.offsets[i]=-$('offset').value;schedule()};$('extension').oninput=()=>{config.extension=+$('extension').value;schedule()};$('copy-notes').onclick=async()=>{try{await navigator.clipboard.writeText($('sequence').value);toast('音符序列已复制')}catch{toast('请选择音符序列后复制')}};
let audio,playing=false,playTimer;
$('play').onclick=async()=>{
 if(playing){playing=false;clearTimeout(playTimer);audio?.close();$('play').textContent='▷ 试听';return}
 if(!ready){toast('请先输入有效音符');return}
 const context=new AudioContext();audio=context;await context.resume();playing=true;$('play').textContent='■ 停止';
 const start=context.currentTime+.05,timeline=makeTimeline(config.notes);
 for(const event of timeline.events){const osc=context.createOscillator(),gain=context.createGain(),time=start+event.start;osc.type='triangle';osc.frequency.value=174.614*Math.pow(2,notes.indexOf(event.note)/12);gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(.14,time+.01);gain.gain.exponentialRampToValueAtTime(.001,time+.25);osc.connect(gain);gain.connect(context.destination);osc.start(time);osc.stop(time+.27)}
 playTimer=setTimeout(()=>{if(audio===context){playing=false;$('play').textContent='▷ 试听';context.close()}},timeline.duration*1000+400);
};
// Local STL preview with the same geometry used by all exports.
const host=$('viewport'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,2000);camera.up.set(0,0,1);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=40;controls.maxDistance=350;
scene.add(new THREE.HemisphereLight(0xffffff,0x698076,2.3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-50,-70,150);scene.add(light);const fill=new THREE.DirectionalLight(0xffe5b4,1.4);fill.position.set(70,110,80);scene.add(fill);
const materials=[new THREE.MeshStandardMaterial({color:0x538d82,roughness:.58,metalness:.05}),new THREE.MeshStandardMaterial({color:0xc4cfbe,roughness:.65,metalness:.03}),new THREE.MeshStandardMaterial({color:0xc98c53,roughness:.5})];let mesh,initialCamera=true,shownWidth=null,outsideView=false;
function updateColors(){for(const [i,name] of ['front','back','clip'].entries()){const color=config.colors?.[name]||defaultColors[name];materials[i].color.set(color);$('color-'+name).value=color;$('hex-'+name).textContent=color.toUpperCase()}const palettes={sage:defaultColors,warm:{front:'#ad634c',back:'#eee0c4',clip:'#647079'},mono:{front:'#d5c7b4',back:'#d5c7b4',clip:'#d5c7b4'}};$('palette').value=Object.keys(palettes).find(key=>Object.keys(defaultColors).every(name=>palettes[key][name]===config.colors?.[name]))||'custom'}
for(const name of ['front','back','clip'])$('color-'+name).oninput=()=>{config.colors[name]=$('color-'+name).value;$('palette').value='custom';updateColors();schedule()};
$('palette').onchange=()=>{const palettes={sage:defaultColors,warm:{front:'#ad634c',back:'#eee0c4',clip:'#647079'},mono:{front:'#d5c7b4',back:'#d5c7b4',clip:'#d5c7b4'}};const colors=palettes[$('palette').value];if(colors){config.colors={...colors};updateColors();schedule()}};

function resizeViewer(){const r=host.getBoundingClientRect();if(r.width&&r.height){renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}}
new ResizeObserver(resizeViewer).observe(host);
function resetCamera(){const center=metadata?(metadata.bounds[1]+metadata.bounds[4])/2:37;controls.target.set(0,center,1);const b=metadata?.bounds||[-40,-17,0,40,94,9],radius=Math.hypot(b[3]-b[0],b[4]-b[1],b[5]-b[2])/2;const vfov=THREE.MathUtils.degToRad(camera.fov),hfov=2*Math.atan(Math.tan(vfov/2)*camera.aspect),distance=radius/Math.sin(Math.min(vfov,hfov)/2)*1.06;camera.position.copy(controls.target).add(new THREE.Vector3(outsideView?.1:.85,outsideView?-.3:-1.25,outsideView?-1.4:1.4).normalize().multiplyScalar(distance));controls.maxDistance=Math.max(400,distance*2);controls.update()}
$('reset-camera').onclick=()=>{outsideView=false;resetCamera()};$('outside-camera').onclick=()=>{outsideView=true;resetCamera()};const bottomLight=new THREE.DirectionalLight(0xffffff,2);bottomLight.position.set(-20,-60,-100);scene.add(bottomLight);
function showModel(base64,regions){
 if(mesh){scene.remove(mesh);mesh.traverse(node=>{if(node.isMesh){node.geometry.dispose();if(!materials.includes(node.material))node.material.dispose()}})}
 mesh=new THREE.Group();const loader=new STLLoader();
 for(const region of regions||[{stl:base64,color:config.colors?.front||defaultColors.front,name:'front'}]){
  const bytes=Uint8Array.from(atob(region.stl),c=>c.charCodeAt(0)),geometry=loader.parse(bytes.buffer);
  const index=['front','back','clip'].indexOf(region.name);const material=index>=0?materials[index]:new THREE.MeshStandardMaterial({color:region.color,roughness:.62,metalness:.02});
  mesh.add(new THREE.Mesh(geometry,material));
 }
 scene.add(mesh);if(initialCamera||shownWidth!==metadata.width){resetCamera();initialCamera=false;shownWidth=metadata.width}
}
resetCamera();function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();
function tab(kind){const art=kind==='art';$('viewport').hidden=art;$('artboard').hidden=!art;$('tab-art').classList.toggle('active',art);$('tab-3d').classList.toggle('active',!art);$('tab-art').setAttribute('aria-selected',art);$('tab-3d').setAttribute('aria-selected',!art);if(art)drawArt();else resizeViewer()}
$('tab-3d').onclick=()=>tab('3d');$('tab-art').onclick=()=>tab('art');$('surface').onchange=drawArt;
const canvas=$('canvas'),ctx=canvas.getContext('2d');let canvasScale=1,canvasOrigin=[0,0];
function screenPoint(x,y){return[canvasOrigin[0]+x*canvasScale,canvasOrigin[1]+y*canvasScale]}
function path(contours,transform=(p)=>p){const path=new Path2D();for(const contour of contours){contour.forEach((p,i)=>{const q=transform(p);i?path.lineTo(...q):path.moveTo(...q)});path.closePath()}return path}
function layerPoint(layer,p){const angle=layer.rotation*Math.PI/180;const x=p[0]*layer.width,y=p[1]*layer.width;return[canvasOrigin[0]+layer.x*canvasScale+(x*Math.cos(angle)-y*Math.sin(angle))*canvasScale,canvasOrigin[1]+layer.y*canvasScale+(x*Math.sin(angle)+y*Math.cos(angle))*canvasScale]}
function drawArt(){if($('artboard').hidden)return;const r=canvas.getBoundingClientRect();if(!r.width)return;canvas.width=r.width*devicePixelRatio;canvas.height=r.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,r.width,r.height);const width=metadata?.width||80.25,depth=metadata?.depth||44;canvasScale=Math.min((r.width-64)/width,(r.height-62)/depth);canvasOrigin=[r.width/2,(r.height-depth*canvasScale)/2];const surface=$('surface').value;const contours=metadata?.contours[surface]||[[[-width/2,0],[width/2,0],[width/2,depth],[-width/2,depth]]];const body=path(contours,p=>screenPoint(...p));ctx.fillStyle=config.colors?.[surface]||'#d8e3de';ctx.fill(body,'evenodd');ctx.strokeStyle='#a5bab1';ctx.lineWidth=1;ctx.stroke(body);ctx.save();ctx.clip(body,'evenodd');config.layers.forEach((layer,i)=>{if(!layer.contours||![surface,'both'].includes(layer.target))return;const patches=layer.preserveColors!==false&&layer.regions?layer.regions:[{contours:layer.contours,color:layer.color||'#b65c2f'}];for(const patch of patches){const shape=path(patch.contours,p=>layerPoint(layer,p));ctx.fillStyle=layer.mode==='engrave'?'#253a36':patch.color;ctx.fill(shape,'evenodd')}});ctx.restore();const layer=config.layers[selected];if(layer&&[surface,'both'].includes(layer.target)){ctx.save();const center=screenPoint(layer.x,layer.y);ctx.translate(...center);ctx.rotate(layer.rotation*Math.PI/180);ctx.strokeStyle='#b46a29';ctx.setLineDash([5,4]);const w=layer.width*canvasScale,h=layer.width*layer.aspect*canvasScale;ctx.strokeRect(-w/2-4,-h/2-4,w+8,h+8);ctx.restore()}}
new ResizeObserver(drawArt).observe(canvas);
function renderLayers(){const list=$('layers');list.replaceChildren();config.layers.forEach((layer,i)=>{const b=document.createElement('button');b.className='layer-item'+(i===selected?' active':'');const label=document.createElement('span');label.textContent=layer.kind==='text'?layer.text:layer.name||'图形';const small=document.createElement('small');small.textContent=({emboss:'凸起',engrave:'凹刻',inlay:'平齐嵌色'})[layer.mode];b.append(label,small);b.onclick=()=>selectLayer(i);list.append(b)});$('empty-layers').hidden=config.layers.length>0;$('layer-editor').hidden=selected<0;if(selected>=0){const layer=config.layers[selected];$('text-field').hidden=layer.kind!=='text';$('image-fields').hidden=layer.kind!=='image';$('layer-text').value=layer.text||'';for(const key of ['target','mode','x','y','width','rotation','depth'])$(key).value=layer[key];$('threshold').value=layer.threshold||128;$('invert').checked=!!layer.invert;
 $('art-colors').hidden=layer.mode==='engrave';$('art-color').value=layer.color||'#b65c2f';$('mono-color-field').hidden=!!(layer.regions&&layer.preserveColors!==false);$('svg-colors-label').hidden=!layer.regions;$('preserve-colors').checked=layer.preserveColors!==false;
 const regionList=$('region-colors');regionList.replaceChildren();if(layer.regions&&layer.preserveColors!==false){layer.regions.forEach((region,i)=>{const input=document.createElement('input');input.type='color';input.value=region.color;input.setAttribute('aria-label',`SVG 颜色 ${i+1}`);input.oninput=()=>{region.color=input.value;schedule()};regionList.append(input)})}
 }drawArt()}
function selectLayer(index){selected=index;renderLayers();const layer=config.layers[selected];if(layer){$('surface').value=layer.target==='front'?'front':'back';tab('art');drawArt()}}
async function addLayer(raw){if(config.layers.length>=12){toast('最多 12 个图层');return}try{const art=await(await api('/api/artwork',raw)).json();config.layers.push({...raw,...art,target:'back',x:0,y:40,width:raw.kind==='text'?18:6,rotation:0,depth:.4,mode:'inlay',color:'#b65c2f',preserveColors:true});selectLayer(config.layers.length-1);schedule()}catch(e){toast(e.message)}}
$('add-text').onclick=()=>addLayer({kind:'text',text:'LILT'});let fileKind='svg';$('add-svg').onclick=()=>{fileKind='svg';$('art-file').accept='.svg';$('art-file').click()};$('add-image').onclick=()=>{fileKind='image';$('art-file').accept='image/png,image/jpeg,image/webp';$('art-file').click()};$('art-file').onchange=async()=>{const file=$('art-file').files[0];if(!file)return;if(file.size>5*1024*1024){toast('文件最大 5 MB');return}const selectedKind=fileKind;const reader=new FileReader();reader.onload=()=>addLayer({kind:selectedKind,name:file.name,data:reader.result,threshold:128,invert:false});reader.readAsDataURL(file);$('art-file').value=''};
for(const key of ['target','mode','x','y','width','rotation','depth'])$(key).oninput=()=>{const layer=config.layers[selected];if(!layer)return;layer[key]=['target','mode'].includes(key)?$(key).value:+$(key).value;if(key==='target')$('surface').value=layer.target==='front'?'front':'back';schedule();renderLayers()};
function updateArtwork(){const layer=config.layers[selected];if(!layer)return;delete layer.contours;schedule();}
$('layer-text').oninput=()=>{if(!config.layers[selected])return;config.layers[selected].text=$('layer-text').value;updateArtwork()};$('threshold').oninput=()=>{config.layers[selected].threshold=+$('threshold').value;updateArtwork()};$('invert').onchange=()=>{config.layers[selected].invert=$('invert').checked;updateArtwork()};$('delete-layer').onclick=()=>{config.layers.splice(selected,1);selected=Math.min(selected,config.layers.length-1);renderLayers();schedule()};
$('art-color').oninput=()=>{const layer=config.layers[selected];if(layer){layer.color=$('art-color').value;schedule()}};$('preserve-colors').onchange=()=>{const layer=config.layers[selected];if(layer){layer.preserveColors=$('preserve-colors').checked;renderLayers();schedule()}};
let drag=null;
canvas.onpointerdown=e=>{const r=canvas.getBoundingClientRect(),p=[e.clientX-r.left,e.clientY-r.top],surface=$('surface').value;for(let i=config.layers.length-1;i>=0;i--){const layer=config.layers[i];if(![surface,'both'].includes(layer.target))continue;const center=screenPoint(layer.x,layer.y),angle=-layer.rotation*Math.PI/180,dx=p[0]-center[0],dy=p[1]-center[1],x=dx*Math.cos(angle)-dy*Math.sin(angle),y=dx*Math.sin(angle)+dy*Math.cos(angle);if(Math.abs(x)<layer.width*canvasScale/2+8&&Math.abs(y)<layer.width*layer.aspect*canvasScale/2+8){selected=i;renderLayers();drag={id:e.pointerId,start:p,x:layer.x,y:layer.y};canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';break}}};canvas.onpointermove=e=>{if(!drag)return;const r=canvas.getBoundingClientRect(),layer=config.layers[selected];layer.x=+(drag.x+(e.clientX-r.left-drag.start[0])/canvasScale).toFixed(2);layer.y=+(drag.y+(e.clientY-r.top-drag.start[1])/canvasScale).toFixed(2);$('x').value=layer.x;$('y').value=layer.y;drawArt()};canvas.onpointerup=()=>{if(drag){drag=null;canvas.style.cursor='grab';schedule()}};
for(const button of document.querySelectorAll('[data-export]'))button.onclick=async()=>{if(!ready)return;const fmt=button.dataset.export;button.disabled=true;try{await download(fmt);toast(`${fmt.toUpperCase()} 已导出`)}catch(e){toast(e.message)}finally{button.disabled=!ready}};
$('save-config').onclick=async()=>{config.notes=$('sequence').value;try{await download('json');toast('方案已保存')}catch(e){toast(e.message)}};$('load-config').onclick=()=>$('config-file').click();$('config-file').onchange=async()=>{const file=$('config-file').files[0];if(!file)return;try{const loaded=JSON.parse(await file.text());if(!loaded.notes||!Array.isArray(loaded.layers||[]))throw Error('方案格式无效');config={offsets:[],extension:0,layers:[],...loaded,colors:{...defaultColors,...loaded.colors}};updateColors();$('sequence').value=Array.isArray(config.notes)?config.notes.join(' '):config.notes;$('extension').value=config.extension;selected=config.layers.length?0:-1;updateTuning();renderLayers();schedule();toast('方案已载入')}catch(e){toast(e.message)}$('config-file').value=''};
$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();$('help-dialog').onclick=e=>{if(e.target===$('help-dialog'))$('help-dialog').close()};
window.musicComb={setNotes(sequence){$('sequence').value=sequence;updateTuning();schedule()},getConfig(){return structuredClone(config)},getMetadata(){return metadata}};
updateTuning();renderLayers();generate();
